const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DB='projectSpotlight',STORE='kv';let currentId=null,currentTemplate='split',beforeFile=null,afterFile=null,logoFile=null,deferredPrompt=null;
const defaults={companyName:'YOUR COMPANY',tagline:'Quality work. Beautiful results.',phone:'',website:'',primaryColor:'#0b3a67',accentColor:'#f4c430',logo:null};
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function get(k){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function set(k,v){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function view(id){$$('.view').forEach(v=>v.classList.add('hidden'));$(id).classList.remove('hidden');scrollTo(0,0)}
function fileURL(f){return f?URL.createObjectURL(f):null}
async function brand(){return {...defaults,...await get('brand')}}
async function projects(){return await get('projects')||[]}
async function renderHome(){const ps=await projects(),grid=$('#projectGrid');grid.innerHTML='';$('#emptyState').classList.toggle('hidden',ps.length>0);for(const p of ps.sort((a,b)=>b.updated-a.updated)){const c=document.createElement('article');c.className='project-card';const img=p.after||p.before;c.innerHTML=`${img?'<img>':'<div style="height:190px;background:#d9e2ec"></div>'}<div class="body"><h3>${esc(p.title||'Untitled Project')}</h3><p>${esc(p.category||'Project')} · ${new Date(p.updated).toLocaleDateString()}</p></div>`;if(img)c.querySelector('img').src=fileURL(img);c.onclick=()=>openProject(p.id);grid.append(c)}}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function resetEditor(){currentId=null;beforeFile=afterFile=null;['projectTitle','projectDescription','projectCategory','projectLocation'].forEach(id=>$('#'+id).value='');['beforePreview','afterPreview'].forEach(id=>{$('#'+id).src='';$('#'+id).classList.add('hidden')});$('#beforePrompt').classList.remove('hidden');$('#afterPrompt').classList.remove('hidden');$('#editorHeading').textContent='New Project';draw()}
async function openProject(id){const p=(await projects()).find(x=>x.id===id);if(!p)return;currentId=id;beforeFile=p.before;afterFile=p.after;$('#projectTitle').value=p.title||'';$('#projectDescription').value=p.description||'';$('#projectCategory').value=p.category||'';$('#projectLocation').value=p.location||'';$('#editorHeading').textContent=p.title||'Edit Project';preview('before',beforeFile);preview('after',afterFile);view('#editorView');draw()}
function preview(which,file){const img=$('#'+which+'Preview'),prompt=$('#'+which+'Prompt');if(file){img.src=fileURL(file);img.classList.remove('hidden');prompt.classList.add('hidden')}else{img.classList.add('hidden');prompt.classList.remove('hidden')}}
async function saveProject(){const title=$('#projectTitle').value.trim();if(!title)return toast('Add a project title first.');let ps=await projects();const p={id:currentId||crypto.randomUUID(),title,description:$('#projectDescription').value.trim(),category:$('#projectCategory').value.trim(),location:$('#projectLocation').value.trim(),before:beforeFile,after:afterFile,updated:Date.now()};const i=ps.findIndex(x=>x.id===p.id);i>=0?ps[i]=p:ps.push(p);await set('projects',ps);currentId=p.id;$('#editorHeading').textContent=p.title;toast('Project saved locally.');renderHome()}
async function loadBrand(){const b=await brand();for(const k of ['companyName','tagline','phone','website','primaryColor','accentColor'])$('#'+k).value=b[k]||'';logoFile=b.logo||null;updateBrandPreview()}
async function saveBrand(){const b={};for(const k of ['companyName','tagline','phone','website','primaryColor','accentColor'])b[k]=$('#'+k).value.trim();b.logo=logoFile;await set('brand',b);toast('Brand Kit saved.');updateBrandPreview();draw()}
async function updateBrandPreview(){const b={...defaults};for(const k of ['companyName','tagline','phone','website','primaryColor','accentColor'])if($('#'+k))b[k]=$('#'+k).value||defaults[k];$('#brandNamePreview').textContent=b.companyName;$('#brandTagPreview').textContent=b.tagline;$('#brandCard').style.background=b.primaryColor;const l=$('#brandLogoPreview');l.style.background=b.accentColor;l.innerHTML=logoFile?'<img src="'+fileURL(logoFile)+'">':'PS'}
function loadImage(file){return new Promise(res=>{if(!file)return res(null);const i=new Image;i.onload=()=>res(i);i.src=fileURL(file)})}
function cover(ctx,img,x,y,w,h){if(!img){ctx.fillStyle='#d9e2ec';ctx.fillRect(x,y,w,h);return}const r=Math.max(w/img.width,h/img.height),nw=img.width*r,nh=img.height*r;ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh)}
function txt(ctx,t,x,y,max,size,weight='700',color='#fff'){ctx.fillStyle=color;ctx.font=`${weight} ${size}px Arial,sans-serif`;let words=(t||'').split(/\s+/),line='',lines=[];for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>max&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);lines.slice(0,5).forEach((l,i)=>ctx.fillText(l,x,y+i*size*1.18));return lines.length*size*1.18}
async function draw(){const c=$('#designCanvas');if(!c)return;const portrait=currentTemplate==='portrait',story=currentTemplate==='story';c.width=1080;c.height=story?1920:portrait?1350:1080;const ctx=c.getContext('2d'),b=await brand(),bef=await loadImage(beforeFile),aft=await loadImage(afterFile);ctx.fillStyle=b.primaryColor;ctx.fillRect(0,0,c.width,c.height);
 const title=$('#projectTitle')?.value||'YOUR PROJECT TITLE',desc=$('#projectDescription')?.value||'Add a short description of the work completed.',loc=$('#projectLocation')?.value||'',cat=$('#projectCategory')?.value||'PROJECT SPOTLIGHT';
 if(currentTemplate==='split'){cover(ctx,bef,0,0,540,680);cover(ctx,aft,540,0,540,680);ctx.fillStyle='rgba(16,42,67,.85)';ctx.fillRect(20,20,150,52);ctx.fillRect(560,20,140,52);txt(ctx,'BEFORE',42,58,120,25);txt(ctx,'AFTER',582,58,110,25);ctx.fillStyle=b.accentColor;ctx.fillRect(0,680,1080,14);txt(ctx,title.toUpperCase(),55,770,970,54,'900');txt(ctx,desc,55,840,720,29,'400','#e8eef3');footer(ctx,b,c.height)}
 else if(currentTemplate==='spotlight'){cover(ctx,aft||bef,0,150,1080,650);ctx.fillStyle=b.primaryColor;ctx.fillRect(0,0,1080,150);txt(ctx,b.companyName.toUpperCase(),55,90,650,43,'900');txt(ctx,'PROJECT SPOTLIGHT',650,90,380,38,'900',b.accentColor);ctx.fillStyle=b.primaryColor;ctx.fillRect(0,800,1080,280);txt(ctx,title.toUpperCase(),55,875,970,50,'900');txt(ctx,desc,55,930,930,27,'400','#e8eef3');footer(ctx,b,c.height)}
 else {const heroH=story?1120:760;cover(ctx,aft||bef,0,0,1080,heroH);const grad=ctx.createLinearGradient(0,heroH-350,0,heroH);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(1,b.primaryColor);ctx.fillStyle=grad;ctx.fillRect(0,heroH-350,1080,350);ctx.fillStyle=b.primaryColor;ctx.fillRect(0,heroH,1080,c.height-heroH);txt(ctx,cat.toUpperCase(),55,heroH-90,900,25,'900',b.accentColor);txt(ctx,title.toUpperCase(),55,heroH+85,970,story?64:56,'900');let y=heroH+165;y+=txt(ctx,desc,55,y,930,story?35:29,'400','#e8eef3');if(loc)txt(ctx,loc,55,y+30,900,25,'700',b.accentColor);footer(ctx,b,c.height)}
}
function footer(ctx,b,h){ctx.fillStyle=b.accentColor;ctx.fillRect(55,h-80,80,7);txt(ctx,[b.phone,b.website].filter(Boolean).join('  •  ')||b.tagline,155,h-58,850,23,'700','#fff')}
async function canvasBlob(){await draw();return new Promise((res,rej)=>$('#designCanvas').toBlob(b=>b?res(b):rej(new Error('Could not render image')),'image/jpeg',.94))}
async function download(){const blob=await canvasBlob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(($('#projectTitle').value||'project-spotlight').toLowerCase().replace(/[^a-z0-9]+/g,'-'))+'.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function share(){const blob=await canvasBlob(),f=new File([blob],'project-spotlight.jpg',{type:'image/jpeg'});if(navigator.canShare?.({files:[f]}))try{await navigator.share({title:$('#projectTitle').value||'Project Spotlight',text:$('#projectDescription').value,files:[f]});catch(e){}else{download();toast('Sharing files is not supported here — exported JPG instead.')}}
$('#newProjectBtn').onclick=()=>{resetEditor();view('#editorView')};$('#brandBtn').onclick=()=>{loadBrand();view('#brandView')};$$('[data-home]').forEach(b=>b.onclick=()=>{renderHome();view('#homeView')});$('#saveProjectBtn').onclick=saveProject;$('#saveBrandBtn').onclick=saveBrand;$('#downloadBtn').onclick=download;$('#shareBtn').onclick=share;
$('#beforeInput').onchange=e=>{beforeFile=e.target.files[0];preview('before',beforeFile);draw()};$('#afterInput').onchange=e=>{afterFile=e.target.files[0];preview('after',afterFile);draw()};$('#logoInput').onchange=e=>{logoFile=e.target.files[0];updateBrandPreview()};
['projectTitle','projectDescription','projectCategory','projectLocation'].forEach(id=>$('#'+id).addEventListener('input',draw));['companyName','tagline','phone','website','primaryColor','accentColor'].forEach(id=>$('#'+id).addEventListener('input',updateBrandPreview));
$$('#templatePicker button').forEach(b=>b.onclick=()=>{$$('#templatePicker button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentTemplate=b.dataset.template;draw()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
window.addEventListener('error',e=>{console.error(e.error||e.message);toast('App error: '+(e.message||'unknown error'))});
window.addEventListener('unhandledrejection',e=>{console.error(e.reason);toast('App error: '+(e.reason?.message||e.reason||'unknown error'))});
// Service worker temporarily disabled while stabilizing prototype.
renderHome().catch(e=>{console.error(e);toast('Could not load local project storage.')});